engines:
  rubocop:
    enabled: true
    checks:
      Rubocop/Style/StringLiterals:
        enabled: false
      Rubocop/Style/PercentLiteralDelimiters:
        enabled: false
ratings:
  paths:
  - "**.rb"