---
driver:
  name: vagrant
  customize:
    memory: '1024'

provisioner:
  name: chef_solo
  deprecations_as_errors: true
  chef_omnibus_url: https://omnitruck.cinc.sh/install.sh
  chef_omnibus_root: /opt/cinc

verifier:
  name: inspec

platforms:
  - name: ubuntu-20.04
    run_list:
    - recipe[apt]

suites:
  - name: default
    run_list:
    - recipe[build-essential]
    - recipe[backup_test::default]
  - name: disable
    run_list:
    - recipe[build-essential]
    - recipe[backup_test::disable]
  - name: remove
    run_list:
    - recipe[build-essential]
    - recipe[backup_test::remove]
