---
driver:
  name: vagrant
  customize:
    memory: '1024'

provisioner:
  name: chef_solo
  deprecations_as_errors: true

platforms:
  - name: ubuntu-16.04
    run_list:
    - recipe[apt]
  - name: centos-6.6
  - name: debian-8.1
    run_list:
    - recipe[apt]

suites:
  - name: default
    run_list:
    - recipe[build-essential]
    - recipe[backup_test::default]
  - name: disable
    run_list:
    - recipe[build-essential]
    - recipe[backup_test::disable]
  - name: remove
    run_list:
    - recipe[build-essential]
    - recipe[backup_test::remove]
